# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: def.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='def.proto',
  package='ds_homework2',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tdef.proto\x12\x0c\x64s_homework2\"\x15\n\x06Sensor\x12\x0b\n\x03uid\x18\x01 \x01(\x05\"\xb7\x01\n\x12SensorInfoResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12;\n\x05state\x18\x02 \x01(\x0e\x32,.ds_homework2.SensorInfoResponse.SensorState\x12\x10\n\x08latitude\x18\x03 \x01(\x02\x12\x11\n\tlongitude\x18\x04 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\x02\"\x1f\n\x0bSensorState\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\"&\n\x0fTemperatureData\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\"L\n\x05Image\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\x12\x10\n\x08\x66rame_id\x18\x04 \x01(\x05\"B\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"\xae\x01\n\tDetection\x12/\n\x0c\x62ounding_box\x18\x01 \x01(\x0b\x32\x19.ds_homework2.BoundingBox\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x05\x12\x32\n\x08\x63\x61tegory\x18\x03 \x01(\x0e\x32 .ds_homework2.Detection.Category\"*\n\x08\x43\x61tegory\x12\n\n\x06Person\x10\x00\x12\x07\n\x03\x43\x61r\x10\x01\x12\t\n\x05Truck\x10\x02\"3\n\nDetections\x12%\n\x04list\x18\x01 \x03(\x0b\x32\x17.ds_homework2.Detection\"K\n\x0fSummaryResponse\x12\x12\n\nnum_people\x18\x01 \x01(\x05\x12\x10\n\x08num_cars\x18\x02 \x01(\x05\x12\x12\n\nnum_trucks\x18\x03 \x01(\x05\x32\x9e\x01\n\x11TemperatureSensor\x12\x44\n\nSensorInfo\x12\x14.ds_homework2.Sensor\x1a .ds_homework2.SensorInfoResponse\x12\x43\n\nSensorData\x12\x14.ds_homework2.Sensor\x1a\x1d.ds_homework2.TemperatureData0\x01\x32\x98\x01\n\x0fObjectDetection\x12H\n\x10SummaryDetection\x12\x13.ds_homework2.Image\x1a\x1d.ds_homework2.SummaryResponse(\x01\x12;\n\x06\x44\x65tect\x12\x13.ds_homework2.Image\x1a\x18.ds_homework2.Detections(\x01\x30\x01\x62\x06proto3'
)



_SENSORINFORESPONSE_SENSORSTATE = _descriptor.EnumDescriptor(
  name='SensorState',
  full_name='ds_homework2.SensorInfoResponse.SensorState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=203,
  serialized_end=234,
)
_sym_db.RegisterEnumDescriptor(_SENSORINFORESPONSE_SENSORSTATE)

_DETECTION_CATEGORY = _descriptor.EnumDescriptor(
  name='Category',
  full_name='ds_homework2.Detection.Category',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Person', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Car', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Truck', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=555,
  serialized_end=597,
)
_sym_db.RegisterEnumDescriptor(_DETECTION_CATEGORY)


_SENSOR = _descriptor.Descriptor(
  name='Sensor',
  full_name='ds_homework2.Sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='ds_homework2.Sensor.uid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=48,
)


_SENSORINFORESPONSE = _descriptor.Descriptor(
  name='SensorInfoResponse',
  full_name='ds_homework2.SensorInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ds_homework2.SensorInfoResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='ds_homework2.SensorInfoResponse.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='ds_homework2.SensorInfoResponse.latitude', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='ds_homework2.SensorInfoResponse.longitude', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='ds_homework2.SensorInfoResponse.altitude', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENSORINFORESPONSE_SENSORSTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=234,
)


_TEMPERATUREDATA = _descriptor.Descriptor(
  name='TemperatureData',
  full_name='ds_homework2.TemperatureData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='ds_homework2.TemperatureData.temperature', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=274,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='ds_homework2.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='ds_homework2.Image.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='ds_homework2.Image.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='ds_homework2.Image.image_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='ds_homework2.Image.frame_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=352,
)


_BOUNDINGBOX = _descriptor.Descriptor(
  name='BoundingBox',
  full_name='ds_homework2.BoundingBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ds_homework2.BoundingBox.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='ds_homework2.BoundingBox.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='ds_homework2.BoundingBox.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='ds_homework2.BoundingBox.height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=420,
)


_DETECTION = _descriptor.Descriptor(
  name='Detection',
  full_name='ds_homework2.Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bounding_box', full_name='ds_homework2.Detection.bounding_box', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='ds_homework2.Detection.frame_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='category', full_name='ds_homework2.Detection.category', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DETECTION_CATEGORY,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=597,
)


_DETECTIONS = _descriptor.Descriptor(
  name='Detections',
  full_name='ds_homework2.Detections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='ds_homework2.Detections.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=599,
  serialized_end=650,
)


_SUMMARYRESPONSE = _descriptor.Descriptor(
  name='SummaryResponse',
  full_name='ds_homework2.SummaryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_people', full_name='ds_homework2.SummaryResponse.num_people', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_cars', full_name='ds_homework2.SummaryResponse.num_cars', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_trucks', full_name='ds_homework2.SummaryResponse.num_trucks', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=652,
  serialized_end=727,
)

_SENSORINFORESPONSE.fields_by_name['state'].enum_type = _SENSORINFORESPONSE_SENSORSTATE
_SENSORINFORESPONSE_SENSORSTATE.containing_type = _SENSORINFORESPONSE
_DETECTION.fields_by_name['bounding_box'].message_type = _BOUNDINGBOX
_DETECTION.fields_by_name['category'].enum_type = _DETECTION_CATEGORY
_DETECTION_CATEGORY.containing_type = _DETECTION
_DETECTIONS.fields_by_name['list'].message_type = _DETECTION
DESCRIPTOR.message_types_by_name['Sensor'] = _SENSOR
DESCRIPTOR.message_types_by_name['SensorInfoResponse'] = _SENSORINFORESPONSE
DESCRIPTOR.message_types_by_name['TemperatureData'] = _TEMPERATUREDATA
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['BoundingBox'] = _BOUNDINGBOX
DESCRIPTOR.message_types_by_name['Detection'] = _DETECTION
DESCRIPTOR.message_types_by_name['Detections'] = _DETECTIONS
DESCRIPTOR.message_types_by_name['SummaryResponse'] = _SUMMARYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sensor = _reflection.GeneratedProtocolMessageType('Sensor', (_message.Message,), {
  'DESCRIPTOR' : _SENSOR,
  '__module__' : 'def_pb2'
  # @@protoc_insertion_point(class_scope:ds_homework2.Sensor)
  })
_sym_db.RegisterMessage(Sensor)

SensorInfoResponse = _reflection.GeneratedProtocolMessageType('SensorInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENSORINFORESPONSE,
  '__module__' : 'def_pb2'
  # @@protoc_insertion_point(class_scope:ds_homework2.SensorInfoResponse)
  })
_sym_db.RegisterMessage(SensorInfoResponse)

TemperatureData = _reflection.GeneratedProtocolMessageType('TemperatureData', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATUREDATA,
  '__module__' : 'def_pb2'
  # @@protoc_insertion_point(class_scope:ds_homework2.TemperatureData)
  })
_sym_db.RegisterMessage(TemperatureData)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'def_pb2'
  # @@protoc_insertion_point(class_scope:ds_homework2.Image)
  })
_sym_db.RegisterMessage(Image)

BoundingBox = _reflection.GeneratedProtocolMessageType('BoundingBox', (_message.Message,), {
  'DESCRIPTOR' : _BOUNDINGBOX,
  '__module__' : 'def_pb2'
  # @@protoc_insertion_point(class_scope:ds_homework2.BoundingBox)
  })
_sym_db.RegisterMessage(BoundingBox)

Detection = _reflection.GeneratedProtocolMessageType('Detection', (_message.Message,), {
  'DESCRIPTOR' : _DETECTION,
  '__module__' : 'def_pb2'
  # @@protoc_insertion_point(class_scope:ds_homework2.Detection)
  })
_sym_db.RegisterMessage(Detection)

Detections = _reflection.GeneratedProtocolMessageType('Detections', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONS,
  '__module__' : 'def_pb2'
  # @@protoc_insertion_point(class_scope:ds_homework2.Detections)
  })
_sym_db.RegisterMessage(Detections)

SummaryResponse = _reflection.GeneratedProtocolMessageType('SummaryResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARYRESPONSE,
  '__module__' : 'def_pb2'
  # @@protoc_insertion_point(class_scope:ds_homework2.SummaryResponse)
  })
_sym_db.RegisterMessage(SummaryResponse)



_TEMPERATURESENSOR = _descriptor.ServiceDescriptor(
  name='TemperatureSensor',
  full_name='ds_homework2.TemperatureSensor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=730,
  serialized_end=888,
  methods=[
  _descriptor.MethodDescriptor(
    name='SensorInfo',
    full_name='ds_homework2.TemperatureSensor.SensorInfo',
    index=0,
    containing_service=None,
    input_type=_SENSOR,
    output_type=_SENSORINFORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SensorData',
    full_name='ds_homework2.TemperatureSensor.SensorData',
    index=1,
    containing_service=None,
    input_type=_SENSOR,
    output_type=_TEMPERATUREDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEMPERATURESENSOR)

DESCRIPTOR.services_by_name['TemperatureSensor'] = _TEMPERATURESENSOR


_OBJECTDETECTION = _descriptor.ServiceDescriptor(
  name='ObjectDetection',
  full_name='ds_homework2.ObjectDetection',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=891,
  serialized_end=1043,
  methods=[
  _descriptor.MethodDescriptor(
    name='SummaryDetection',
    full_name='ds_homework2.ObjectDetection.SummaryDetection',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_SUMMARYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Detect',
    full_name='ds_homework2.ObjectDetection.Detect',
    index=1,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_DETECTIONS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OBJECTDETECTION)

DESCRIPTOR.services_by_name['ObjectDetection'] = _OBJECTDETECTION

# @@protoc_insertion_point(module_scope)
