# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import def_pb2 as def__pb2


class TemperatureSensorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SensorInfo = channel.unary_unary(
                '/ds_homework2.TemperatureSensor/SensorInfo',
                request_serializer=def__pb2.Sensor.SerializeToString,
                response_deserializer=def__pb2.SensorInfoResponse.FromString,
                )
        self.SensorData = channel.unary_stream(
                '/ds_homework2.TemperatureSensor/SensorData',
                request_serializer=def__pb2.Sensor.SerializeToString,
                response_deserializer=def__pb2.TemperatureData.FromString,
                )


class TemperatureSensorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SensorInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SensorData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemperatureSensorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SensorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SensorInfo,
                    request_deserializer=def__pb2.Sensor.FromString,
                    response_serializer=def__pb2.SensorInfoResponse.SerializeToString,
            ),
            'SensorData': grpc.unary_stream_rpc_method_handler(
                    servicer.SensorData,
                    request_deserializer=def__pb2.Sensor.FromString,
                    response_serializer=def__pb2.TemperatureData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ds_homework2.TemperatureSensor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TemperatureSensor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SensorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ds_homework2.TemperatureSensor/SensorInfo',
            def__pb2.Sensor.SerializeToString,
            def__pb2.SensorInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ds_homework2.TemperatureSensor/SensorData',
            def__pb2.Sensor.SerializeToString,
            def__pb2.TemperatureData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ObjectDetectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SummaryDetection = channel.stream_unary(
                '/ds_homework2.ObjectDetection/SummaryDetection',
                request_serializer=def__pb2.Image.SerializeToString,
                response_deserializer=def__pb2.SummaryResponse.FromString,
                )
        self.Detect = channel.stream_stream(
                '/ds_homework2.ObjectDetection/Detect',
                request_serializer=def__pb2.Image.SerializeToString,
                response_deserializer=def__pb2.Detections.FromString,
                )


class ObjectDetectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SummaryDetection(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Detect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SummaryDetection': grpc.stream_unary_rpc_method_handler(
                    servicer.SummaryDetection,
                    request_deserializer=def__pb2.Image.FromString,
                    response_serializer=def__pb2.SummaryResponse.SerializeToString,
            ),
            'Detect': grpc.stream_stream_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=def__pb2.Image.FromString,
                    response_serializer=def__pb2.Detections.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ds_homework2.ObjectDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ObjectDetection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SummaryDetection(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/ds_homework2.ObjectDetection/SummaryDetection',
            def__pb2.Image.SerializeToString,
            def__pb2.SummaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Detect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ds_homework2.ObjectDetection/Detect',
            def__pb2.Image.SerializeToString,
            def__pb2.Detections.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
